# Generated by Django 3.1.4 on 2020-12-21 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditorums', '0001_initial'),
        ('movies', '0004_remove_movie_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_date', models.DateField()),
                ('time', models.TimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorums.auditoruim')),
            ],
        ),
    ]
