# Generated by Django 3.1.4 on 2020-12-20 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20201220_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 17, 13, 43, 500370)),
        ),
    ]
