# Generated by Django 3.1.4 on 2020-12-21 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20201220_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 18, 48, 21, 855481)),
        ),
    ]
