# Generated by Django 3.1.4 on 2020-12-19 17:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('duraration', models.CharField(max_length=150)),
                ('trailer', models.FileField(upload_to='videos/%Y/%m/%d/')),
                ('images', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('rated', models.CharField(choices=[('PG', 'Rated Pg'), ('18+', 'Rated 18'), ('16+', 'Rated 16'), ('21+', 'Rated 21'), ('13+', 'Rated 13')], default='PG', max_length=50)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=250)),
                ('cast', models.TextField()),
                ('description', models.TextField()),
                ('release_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
            ],
        ),
    ]
